name: Build
'on':
  push:
    tags:
    - '*'
    - '!*-*'
  workflow_dispatch: {}
jobs:
  job:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Get version from tag
      run: |
        set -x
        echo "BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      id: version
    - name: Docker login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username darkwind8 --password-stdin
    - name: Checkout Freelancer
      uses: darklab8/infra/.github/actions/checkout-freelancer@master
      with:
        freelancer-mod: vanilla
        freelancer-folder: ${{ github.workspace }}/Freelancer
        ssh-key-base64-vanilla: ${{ secrets.ID_RSA_FILES_FREELANCER_VANILLA }}
    - name: Build image darkwind8/fl-server-vanilla
      run: |
        set -ex
        export tag_version=${{ steps.version.outputs.BUILD_VERSION }}
        docker build --build-arg "BUILD_VERSION=${tag_version}" --tag darkwind8/fl-server-vanilla:${tag_version} .

        docker push darkwind8/fl-server-vanilla:${tag_version}
        sleep 5
